version: "3"
services:
  mongo:
    image: mongo
    container_name: mongodb
  web:
    container_name: server
    build: .
    ports:
      - "8000:8000"
    command: sh -c
      "node dev-data/setup --setcounter tempID
      && node dev-data/setup --createadmin admin ${ADMIN_EMAIL} ${ADMIN_PASS}
      && node server.js"
    depends_on:
      - mongo
